"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Search, Zap, Brain, BarChart3 } from "lucide-react";

const features = [
  {
    icon: Search,
    title: "Semantic Search",
    description:
      "Advanced vector embeddings find the most relevant information from my portfolio across all projects and experiences.",
  },
  {
    icon: Brain,
    title: "AI-Powered Responses",
    description:
      "Natural language responses generated by LLMs, combining retrieved documents for context-aware answers.",
  },
  {
    icon: Zap,
    title: "Instant Answers",
    description:
      "Get quick, accurate answers about my projects, skills, and experiences without searching through documentation.",
  },
  {
    icon: BarChart3,
    title: "Multi-Domain Knowledge",
    description:
      "Comprehensive coverage of my work across different projects, technologies, and domains.",
  },
];

export function Features() {
  return (
    <section id="features" className="py-20 sm:py-32 bg-secondary/30">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold mb-4 text-balance">
            Powered by Advanced RAG
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto text-balance">
            Combining semantic search, vector embeddings, and AI for
            contextually accurate answers
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card
                key={index}
                className="border border-border hover:border-primary/50 transition-colors group"
              >
                <CardHeader>
                  <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition">
                    <Icon className="h-6 w-6 text-primary" />
                  </div>
                  <CardTitle>{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-base">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
}
